#!/bin/bash

RUNLEVEL=$1

if [ -z '${RUNLEVEL}' ]; then 
	echo "Runlevel not supplied."
	exit 1
	fi

case ${RUNLEVEL} in 
	0)
	echo "Shutting down system ... "
	/sbin/shutdown -hfn now 
	;;
	1)
	echo "Entering runlevel ${RUNLEVEL} ... "
	;;
	2)
	echo "Entering runlevel ${RUNLEVEL} ... "
	;;
	3)
	echo "Entering runlevel ${RUNLEVEL} ... "
	;;
	4)
	echo "Entering runlevel ${RUNLEVEL} ... "
	;;
	5)
	echo "Entering runlevel ${RUNLEVEL} ... "
	;;
	6)
	echo "Rebooting system ... "	
	/sbin/shutdown -rfn now
	;;
	*)
	echo "Invalid ${RUNLEVEL}"
	exit 1
	;;
esac

exit 0

