#!/bin/bash

RUNLEVEL=$1

if [ -z '${RUNLEVEL}' ]; then 
	echo "Runlevel not supplied."
	exit 1
	fi

start_services() {
	RUNLEVEL=${1}
	for SERVICE in `ls -1 /etc/rc${RUNLEVEL}.d/S* 2>/dev/null | sort -n` ; do
		echo -n "Starting service ${SERVICE} ..."
		${SERVICE} start 1>/dev/null 2>&1
		STATUS=$?
		if [ $STATUS -gt 0 ]; then 
				echo "\x1b[31m[FAILED ($STATUS)]\x1b[0m"
			else
				echo "\x1b[32m[OK]\x1b[0m"
			fi
		done

}	

echo ""

case ${RUNLEVEL} in 
	0)
	echo "Shutting down system ... "
	/sbin/shutdown -hfn now 
	;;
	1)
	echo "Entering runlevel ${RUNLEVEL} ... "
	start_services 1 
	;;
	2)
	echo "Entering runlevel ${RUNLEVEL} ... "
	start_services 2 
	;;
	3)
	echo "Entering runlevel ${RUNLEVEL} ... "
	start_services 3 
	;;
	4)
	echo "Entering runlevel ${RUNLEVEL} ... "
	start_services 4 
	;;
	5)
	echo "Entering runlevel ${RUNLEVEL} ... "
	start_services 5
	;;
	6)
	echo "Rebooting system ... "	
	/sbin/shutdown -rfn now
	;;
	*)
	echo "Invalid ${RUNLEVEL}"
	exit 1
	;;
esac
echo ""

exit 0

