#!/bin/bash

# suppress all kernel logging to console except panics

/bin/dmesg -n 1
mount proc /proc -t proc
mkdir -p /dev/pts
mount devpts /dev/pts -t devpts
/usr/5bin/hostname headrat
mount -a

# Delete ICE locks 
rm -rf /tmp/.ICE-unix
mkdir -p /tmp/.ICE-unix
chown root:root /tmp/.ICE-unix/
chmod 1777 /tmp/.ICE-unix

exit 0

