#!/bin/sh
########################################################################
# Begin udev
#
# Description : Udev cold-plugging script
#
# Authors     : Zack Winkles, Alexander E. Patrakov
#               DJ Lucas - dj@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            udev $time
# Required-Start:      localnet
# Should-Start:        modules
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Populates /dev with device nodes.
# Description:         Mounts a tempfs on /dev and starts the udevd daemon.
#                      Device nodes are created as defined by udev.
# X-LFS-Provided-By:   LFS
### END INIT INFO

#. /lib/lsb/init-functions

case "${1}" in
   start)
      echo "Populating /dev with device nodes... "
      if ! grep -q '[[:space:]]sysfs' /proc/mounts; then
         echo "failure"
         msg="FAILURE:\n\nUnable to create "
         msg="${msg}devices without a SysFS filesystem\n\n"
         msg="${msg}After you press Enter, this system "
         msg="${msg}will be halted and powered off.\n\n"
         echo "$msg"
         echo "Press Enter to continue..."
         read ENTER
	 /sbin/telinit 0
      fi

      # Start the udev daemon to continually watch for, and act on,
      # uevents
      /usr/lib/systemd/systemd-udevd --daemon

      # Now traverse /sys in order to "coldplug" devices that have
      # already been discovered
      /usr/bin/udevadm trigger --action=add    --type=subsystems
      /usr/bin/udevadm trigger --action=add    --type=devices
      /usr/bin/udevadm trigger --action=change --type=devices

      # Now wait for udevd to process the uevents we triggered
#      if ! is_true "$OMIT_UDEV_SETTLE"; then
         /usr/bin/udevadm settle
#      fi

      # If any LVM based partitions are on the system, ensure they
      # are activated so they can be used.
#      if [ -x /sbin/vgchange ]; then /sbin/vgchange -a y >/dev/null; fi 

      echo "success" 
      ;;

   *)
      echo "Usage ${0} {start}"
      exit 1
      ;;
esac

exit 0

# End udev
