#!/bin/sh
########################################################################
# Begin crond
#
# Description : Fcron cron init script
#
# Author      : Name - name@linuxfromscratch.org
#
# Version     : BLFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            crond
# Required-Start:      $local_fs $network
# Should-Start:        networkmanager wicd
# Required-Stop:       $local_fs $network
# Should-Stop:         networkmanager wicd
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts crond.
# Description:         Starts crond daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/usr/sbin/crond"

#$LastChangedBy: dj $
#$Date: 2020-08-17 01:20:21 -0500 (Mon, 17 Aug 2020) $

case "$1" in
   start)
      log_info_msg "Starting crond..."
      start_daemon ${BIN_FILE}
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping crond..."
      killproc ${BIN_FILE}
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc ${BIN_FILE}
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/crond
