/* XPM */
static char *Dtinfo_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 160 2 ",
"   c None",
".  c #4F970C",
"X  c #50960C",
"o  c #549E0D",
"O  c #559715",
"+  c #579A15",
"@  c #599D16",
"#  c #5C9C1D",
"$  c #5CAC0D",
"%  c #5EB20D",
"&  c #5CA515",
"*  c #5FAB15",
"=  c #5EA11D",
"-  c #61B60E",
";  c #63BA0F",
":  c #61AE16",
">  c #60A41F",
",  c #62AB1A",
"<  c #63B414",
"1  c #65BD10",
"2  c #6ABF17",
"3  c #66B519",
"4  c #6AB81D",
"5  c #5E9D21",
"6  c #629F26",
"7  c #64A524",
"8  c #65A22B",
"9  c #68A42E",
"0  c #67A828",
"q  c #6AA92C",
"w  c #6CB623",
"e  c #6DBA23",
"r  c #6CB029",
"t  c #70BB27",
"y  c #71BA2A",
"u  c #6EAC32",
"i  c #72AA3C",
"p  c #74B535",
"a  c #76BB33",
"s  c #78BA36",
"d  c #75B339",
"f  c #79B63F",
"g  c #7ABB3B",
"h  c #67C011",
"j  c #6AC512",
"k  c #6ECA14",
"l  c #71CE15",
"z  c #70C71B",
"x  c #73CE1B",
"c  c #73D216",
"v  c #75D319",
"b  c #79D61E",
"n  c #74C624",
"m  c #77C728",
"M  c #7ACB2B",
"N  c #7CD722",
"B  c #7EDA25",
"V  c #7DD529",
"C  c #7FD928",
"Z  c #7EC23C",
"A  c #7FC938",
"S  c #7BB741",
"D  c #80DB27",
"F  c #81D62D",
"G  c #84DD2C",
"H  c #82CB3B",
"J  c #81D331",
"K  c #84DB31",
"L  c #87D639",
"P  c #8ADB3B",
"I  c #87E030",
"U  c #8AE234",
"Y  c #8EE33A",
"T  c #81BF46",
"R  c #84BF49",
"E  c #84C247",
"W  c #87CE42",
"Q  c #8ACE46",
"!  c #85C24B",
"~  c #8CCC4D",
"^  c #8EDB41",
"/  c #91DD45",
"(  c #94DE4A",
")  c #8DC755",
"_  c #8FC957",
"`  c #8EC558",
"'  c #91CE56",
"]  c #93CC5B",
"[  c #91D253",
"{  c #96DE51",
"}  c #98DF53",
"|  c #97D55B",
" . c #98D15F",
".. c #92E341",
"X. c #95E14B",
"o. c #98E24F",
"O. c #97E150",
"+. c #9BE354",
"@. c #9EE35A",
"#. c #A0E55E",
"$. c #95C963",
"%. c #9BD363",
"&. c #9FDA64",
"*. c #9ED668",
"=. c #A1DC66",
"-. c #A4DE6B",
";. c #A6DB73",
":. c #A8DD73",
">. c #AADC7A",
",. c #A2E363",
"<. c #A6E965",
"1. c #A8EA67",
"2. c #A6E16D",
"3. c #A9E56E",
"4. c #AAEA6B",
"5. c #ACE475",
"6. c #ADEA72",
"7. c #AFE679",
"8. c #B0EB76",
"9. c #B1E77C",
"0. c #B2EA7C",
"q. c #BABDB6",
"w. c #B4D197",
"e. c #B7D29D",
"r. c #AFE080",
"t. c #B5E686",
"y. c #B6EB81",
"u. c #B8ED85",
"i. c #B7E689",
"p. c #BCEE8C",
"a. c #BFEF92",
"s. c #B5C2A8",
"d. c #BED6A7",
"f. c #BCC1B5",
"g. c #BEC9B3",
"h. c #BEC3B9",
"j. c #C1EF95",
"k. c #C5EF9C",
"l. c #C1F093",
"z. c #C7F39C",
"x. c #C1D8AC",
"c. c #C1C4BC",
"v. c #C7EEA0",
"b. c #C9EEA4",
"n. c #CDEFAB",
"m. c #CBF2A5",
"M. c #CFF7A8",
"N. c #D1F7AC",
"B. c #D1F3B0",
"V. c #D6FAB4",
"C. c #CACEC5",
"Z. c #CBD1C4",
"A. c #D6D7D3",
"S. c #DEE0DC",
"D. c #E0E3DF",
"F. c #E1E4E0",
"G. c #EEEEED",
"H. c #F0F0EF",
"J. c #F4F4F3",
"K. c #FBFBFB",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                  v c c c c c c c c c c c c c c c c c c c c c c c c c c c c c                   ",
"                v y.N.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.c                   ",
"              v M.B.x.f.q.q.q.f.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.h.v                   ",
"            v 0.m.c.D.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.J.c.V                   ",
"            c M.e.F.J.J.K.J.J.J.J.J.J.K.J.J.J.K.J.J.J.J.J.J.J.J.J.J.J.J.J.C.W                   ",
"            v V.f.G.J.H.H.J.H.H.H.J.H.J.H.G.H.H.J.J.H.H.G.G.G.G.G.G.G.G.G.A.$.                  ",
"            c N.w.S.H.G.H.H.H.H.G.H.H.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.F.s.                  ",
"            c a.j.h.S.H.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.K.J.J.J.J.J.J.J.J.J.C.$.c               ",
"            c 2.z.m.x.f.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.g.c               ",
"            c 2.^ l.M.N.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.c               ",
"            c ,.^ 5.6.&.5.{ / F b c c c c c c c c c c c c c c c c c c c c c c n.c               ",
"            c 2.P 7.5.&.:.{ P J v c c c c c c c c c c c c c c c c c c c c c c n.c               ",
"            c ,.^ 7.7.&.2.{ ^ F v c c c c c c c c c c c c c c c c c c c c c c n.c               ",
"            c &.P 7.7.&.5.{ ^ K b c c c c c v v v c c v c c v c v c v c c c c n.c               ",
"            c ,.^ 7.7.&.2.{ ^ K b v v v v v v c v v v v v c c v v v v v v v v b.c               ",
"            c ,.^ 7.7.&.5.} ^ K x * + + : h < & o + & < 2 : @ + * l v v v v v n.c               ",
"            c #.^ 0.7.*.5.} / J @ E ;.0 O q ] >.t.i.:.' 7 O 0 ;.T @ c v v b v m.c               ",
"            c &.^ 7.7.=.5.} / q ! | # O O 7 { P D D P ( > O X # | ! : b b v b b.c               ",
"            c @.^ 0.0.=.5.} / 6 Q @ O O O O z b v b b 3 O O O O @ W @ b b b b b.l               ",
"            c @.^ 7.0.&.5.@./ u 7 O O O O O : b b b N @ O O O O O > = b b b N v.k               ",
"            c @./ 0.0.=.5.@./ S O O + O + O O , @ # , O O O O O O O a b N N N v.k               ",
"            c @./ 0.0.&.5.@.X.Q u %.d O O O 7 *.t.t.*.7 O O O d %.q A N N N N k.k               ",
"            l } / 9.9.2.5.@.o.y Z O.4.:.q 0 9.X.G G X.9.0 0 :.3.X.g 4 B b B N v.j               ",
"            l @.^ 0.y.&.7.@.X.u A B B ^ p | G B D N D F  .p / B B A , B B B B z.j               ",
"            k } / 9.y.2.7.@.X.8 L B C B = ^ B B D N N D ^ & B D B L # B B B B z.j               ",
"            k } / 0.y.&.9.@.X.u F B B B > V C B D B D B F > D B B C 7 B D B B k.h               ",
"            k } / 9.0.2.9.@.X.S m F D D p n C D D D D D n p D D B n p B D B F k.h               ",
"            j } ^ y.y.-.9.@.o.! t B e 7 # = C D D D D F # # > e B e Z G D D D z.1               ",
"            h } X.0.y.2.9.#.O.[ 7 = # # # # 7 m C C n > # # # # = 7 W D D I D z.1               ",
"            h O.( 0.y.-.9.,.+.a 5 # # # # 5 u ! 9 7 E q # # # # 5 5 w G D G G l.1               ",
"            h O./ y.y.2.9.,.+.u d 5 5 # 5 # -.4.u.p.6.' 5 # 5 # # u 7 F I D I l.1               ",
"            1 ( X.9.y.2.9.#.+.i ;.q 5 # 5 S +.I I I G O.7 5 5 5 9 :.q I I I K l.-               ",
"            1 { X.y.y.2.0.<.+.$.a 2.q 5 5 ! K I I I K I E 5 5 q 2.y ` G K I U l.%               ",
"            1 ( X.0.y.2.0.<.+.0.u s t.d 6 q y M F G M y q 6 d r.a u 5.I I I I l.%               ",
"            1 / X.y.u.2.y.<.+.o.p.] 9 u ) :.' g 7 7 g ' -.) u q $.i.Y I U U U l.%               ",
"            < ^ +.y.u.5.0.<.@.X...8.l.p.4.+.4.0.j.a.0.1.+.6.p.a.8.Y I U I U I l.$               ",
"            o M <.y.u.4.0.<.#.X.U U U U U U U U I U U U U U U U U U U U U U U l.$               ",
"              % } j.u.5.y.<.@.X.Y U U U U U U U U U U U U U U U U U U U U I U a.$               ",
"                $ W 9.u.a.u.0.6.1.1.1.1.4.4.4.6.8.8.8.0.0.0.0.y.y.u.u.u.p.p.p.t.$               ",
"                  X $ $ $ % % % $ $ % $ % $ $ $ % $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ .               ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
