/* XPM */
static char *DtMail_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 155 2 ",
"   c None",
".  c #4E9A06",
"X  c #519C07",
"o  c #539812",
"O  c #5DA21C",
"+  c #62A326",
"@  c #66A52A",
"#  c #69A62E",
"$  c #6CA733",
"%  c #6EAD30",
"&  c #6FAA39",
"*  c #70AE32",
"=  c #73AB3C",
"-  c #76AD41",
";  c #7CB149",
":  c #BF9E02",
">  c #BE9D0C",
",  c #BA9D1A",
"<  c #C19D00",
"1  c #C5A514",
"2  c #C8A817",
"3  c #C3A41D",
"4  c #CCAE25",
"5  c #CDAF2B",
"6  c #CFB12C",
"7  c #CDB234",
"8  c #CEB53E",
"9  c #D0B435",
"0  c #89D93B",
"q  c #89E234",
"w  c #E3CD0D",
"e  c #E3CD15",
"r  c #E6D010",
"t  c #EAD314",
"y  c #EBD51B",
"u  c #D7C03D",
"i  c #EBD723",
"p  c #EED927",
"a  c #E7D42B",
"s  c #E8D42D",
"d  c #EEDA2C",
"f  c #F0DB2B",
"g  c #F2DD32",
"h  c #80B54E",
"j  c #82847F",
"k  c #CEB745",
"l  c #CFB845",
"z  c #87C24F",
"x  c #8AC553",
"c  c #8FC857",
"v  c #94CB5D",
"b  c #92E344",
"n  c #96E24C",
"m  c #9AE253",
"M  c #9DE35A",
"N  c #A0E35E",
"B  c #98CF65",
"V  c #95CB60",
"C  c #9ED36A",
"Z  c #A3D772",
"A  c #A7DA77",
"S  c #A7DA78",
"D  c #A1E462",
"F  c #DBC341",
"G  c #EEDC42",
"H  c #E1CE64",
"J  c #E5D46C",
"K  c #E3D167",
"L  c #E5D471",
"P  c #E8D770",
"I  c #EADC7B",
"U  c #E9D874",
"Y  c #F2E56F",
"T  c #F3E572",
"R  c #F3E67A",
"E  c #878984",
"W  c #888A85",
"Q  c #8D8E89",
"!  c #838580",
"~  c #8F908C",
"^  c #979683",
"/  c #979A95",
"(  c #ACA991",
")  c #ADBD9D",
"_  c #A3A5A1",
"`  c #B1BFA2",
"'  c #B0B1AE",
"]  c #B4B6B2",
"[  c #B7B9B6",
"{  c #B9BBB6",
"}  c #BCBDB9",
"|  c #C0BEAA",
" . c #B6EB84",
".. c #B8EA87",
"X. c #B9EC88",
"o. c #B3E681",
"O. c #B3C2A5",
"+. c #B8C3AE",
"@. c #BBC5B2",
"#. c #ECDE81",
"$. c #C1ED95",
"%. c #C7F19F",
"&. c #EEE185",
"*. c #F1E684",
"=. c #F5E984",
"-. c #F1E489",
";. c #F5EA8D",
":. c #F8EC8B",
">. c #F8EB86",
",. c #F5EB93",
"<. c #F6ED9A",
"1. c #C9C7B7",
"2. c #C0C3BC",
"3. c #C2CABB",
"4. c #C8D8B9",
"5. c #DCD7B5",
"6. c #C7EDA2",
"7. c #CBF2A5",
"8. c #CCF1A9",
"9. c #F8EFA9",
"0. c #F6EEAC",
"q. c #F9F1AC",
"w. c #E9E2BE",
"e. c #FAF2B1",
"r. c #C4C5C3",
"t. c #C6CAC3",
"y. c #C8CAC6",
"u. c #CCCECA",
"i. c #CBD1C7",
"p. c #CED1CB",
"a. c #D1D4CE",
"s. c #D8D7CD",
"d. c #D0D1C3",
"f. c #D4D5D2",
"g. c #D6D9D4",
"h. c #D9DCD6",
"j. c #DCDEDA",
"k. c #D7E6CA",
"l. c #DEE1DC",
"z. c #EAE5C5",
"x. c #E9E5CC",
"c. c #E6E5D7",
"v. c #E1E3DE",
"b. c #F0EBD1",
"n. c #E4E6E2",
"m. c #E6E8E4",
"M. c #E8EAE6",
"N. c #ECEDEA",
"B. c #EFF0EE",
"V. c #F0F1EF",
"C. c #F7F3E2",
"Z. c #F4F5F4",
"A. c #F7F8F7",
"S. c #F8F8F7",
"D. c #FBFBFA",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                X . X X . . . . X                               ",
"                                                . 7.8.7.7.8.7.%..                               ",
"                                                X 7.q b b q b  ..                               ",
"                                                . 7.q q q q b  ..                               ",
"              ~ W W E E W W W W E E E W E W W W o 6.0 0 0 0 0  .o ! E E E E E W W Q             ",
"            ~ D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.O 7.b b n b b X.O B.A.A.A.A.A.Z.A.N.Q           ",
"            W D.D.D.D.D.D.D.D.Z.A.D.A.Z.Z.Z.Z.V.O 7.n b b b b X.O l.m.m.m.n.n.n.n.Z.W           ",
"            W D.D.D.D.D.D.D.D.D.A.A.A.Z.A.Z.V.Z.o 7.n n n n n X.O l.m.m.m.n.n.n.v.Z.W           ",
"            W D.D.D.D.D.D.D.D.D.A.A.k.O O O O O = 7.n n n n n 7.% O O O O O 4.v.l.Z.E           ",
"            E D.N.Z.D.D.D.D.D.D.A.A.Z.h x 7.8.8.8. .n m m n m  .8.8.8.8.z ; l.l.j.Z.E           ",
"            E D.D.M.Z.D.D.D.D.D.A.A.A.h.= x X.m n m m m m m m n n M  .x = i.f.a.l.Z.E           ",
"            Q D.S.D.l.Z.D.D.S.S.D.A.A.Z.s.& c  .M m m M m m m m M o.c & t.f.u.l.l.Z.W           ",
"            E D.S.D.S.f.S.D.S.S.A.A.A.Z.Z.p.$ v  .M m M M M M M ..V $ 3.f.y.l.l.l.A.E           ",
"            W D.S.D.D.S.u.S.S.S.A.A.Z.Z.Z.V.3.# B  .M M M M M X.B $ @.f.@.j.l.n.l.Z.E           ",
"            W D.S.S.S.S.B.r.S.S.A.Z.A.Z.Z.Z.V.2.@ C X.D D D X.C # @.g.@.j.n.l.l.l.Z.E           ",
"            W D.S.S.S.S.S.n.2.S.A.Z.Z.z.9 w.Z.M.+.+ Z X.D X.Z + +.f.] f.n.v.v.l.l.Z.E           ",
"            W D.Z.S.S.S.A.Z.j.} A.A.z.4 P 4 z.V.M.` + S $.S + O.f.] u.l.v.v.l.l.l.Z.E           ",
"            E D.Z.Z.Z.Z.Z.Z.Z.a.{ b.4 -.<.#.5 x.V.n.) + V + ` f.' r.l.n.n.l.l.l.l.Z.E           ",
"            E S.Z.Z.Z.Z.Z.Z.Z.N.( 3 *.=.y =.#.4 c.V.n.) $ O.f._ _ l.n.v.n.l.l.l.j.Z.E           ",
"            E D.Z.V.Z.Z.Z.V.Z.| 6 I -.t t y ;.I 6 C.D.N.r._ / v.N.[ n.n.l.l.l.j.j.Z.E           ",
"            E D.V.V.V.V.V.Z.1.6 I ;.y w w w e -.L , ^ / _ [ v.m.N.n.@.n.n.l.l.l.j.Z.E           ",
"            E D.V.V.V.V.V.d.7 U ,.y t t t t t i ;.L 7 c.n.n.m.n.n.M.n.y.l.l.j.l.j.Z.E           ",
"            E D.N.V.V.V.s.9 J ,.i t t t t t t t i ,.K 7 n.m.m.n.n.n.n.l.u.j.j.j.l.V.W           ",
"            E D.N.N.B.h.8 K <.p t t t t t t t t t i <.H k c.m.v.n.l.l.m.l.p.l.h.h.Z.E           ",
"            E D.N.N.v.l F ;.R T T G t t t t t G Y T R ;.8 l c.v.n.l.l.l.v.g.a.l.h.V.E           ",
"            E Z.M.n.5.2 1 2 2 1 4 <.y y y y y T 4 1 1 1 1 1 5.n.n.j.l.l.l.l.g.g.j.Z.E           ",
"            E Z.n.j.n.g.a.a.p.a.1 q.i y i i y R 1 r.t.r.t.t.u.l.h.h.k.h.g.g.g.a.a.N.E           ",
"            W M.g.j.j.g.g.f.f.f.1 0.i a p p i R 1 y.u.u.u.u.p.g.f.g.f.f.f.a.a.a.p.n.W           ",
"            Q g.n.l.l.v.l.v.v.l.1 e.d g g d g R 1 g.l.l.l.l.j.v.j.l.j.j.j.j.l.j.j.f.W           ",
"              W E E E E E W E E < e.a s s s s *.> ! W E E E E E E W W W E E E E W W             ",
"                                < e.p f p d f >.:                                               ",
"                                < e.g f g g g :.<                                               ",
"                                < q.:.:.:.:.:.:.<                                               ",
"                                : < < < < < < < :                                               ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
