/* XPM */
static char *Fpapps_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 193 2 ",
"   c None",
".  c #37343A",
"X  c #3A2241",
"o  c #42274A",
"O  c #45294D",
"+  c #412A47",
"@  c #492B51",
"#  c #4F2F58",
"$  c #55335D",
"%  c #5C3A5A",
"&  c #4E3452",
"*  c #5C3565",
"=  c #5B3D64",
"-  c #633E6C",
";  c #414246",
":  c #775457",
">  c #6D485D",
",  c #714D6B",
"<  c #8D5D0F",
"1  c #925F0F",
"2  c #8F5E10",
"3  c #A0670C",
"4  c #A1690E",
"5  c #A36B12",
"6  c #A8731D",
"7  c #AA790A",
"8  c #986E2B",
"9  c #AC7928",
"0  c #81606D",
"q  c #478B06",
"w  c #4E9A06",
"e  c #5C9F17",
"r  c #619F12",
"t  c #5DA11C",
"y  c #9C931C",
"u  c #BB9902",
"i  c #BB9A07",
"p  c #B08B17",
"a  c #ACA31F",
"s  c #B58232",
"d  c #AC813F",
"f  c #B0A93B",
"g  c #C4A100",
"h  c #D7BB19",
"j  c #CCAE12",
"k  c #D8BE3B",
"l  c #D5BB38",
"z  c #CCB230",
"x  c #86D13E",
"c  c #8AE234",
"v  c #EDD402",
"b  c #F1D916",
"n  c #E9CF0C",
"m  c #F4DD23",
"M  c #EED626",
"N  c #F6E135",
"B  c #F9E53F",
"V  c #F6E02D",
"C  c #BF8F44",
"Z  c #AF8B53",
"A  c #A68550",
"S  c #BD8F54",
"D  c #ADA856",
"F  c #83946D",
"G  c #C29C5F",
"H  c #D1B14F",
"J  c #E1AE5F",
"K  c #CBA263",
"L  c #D5A965",
"P  c #D0AD72",
"I  c #D9B377",
"U  c #CAB469",
"Y  c #EABA6F",
"T  c #E9BC77",
"R  c #90D44C",
"E  c #9DE756",
"W  c #A1E85D",
"Q  c #A5E964",
"!  c #ABEA6E",
"~  c #ACEB70",
"^  c #B8E16F",
"/  c #DAC34E",
"(  c #DDC95C",
")  c #E1CD5F",
"_  c #F2DD41",
"`  c #FBE84F",
"'  c #FBE74C",
"]  c #F4E358",
"[  c #E6D572",
"{  c #F6E875",
"}  c #7F5E85",
"|  c #7E6184",
" . c #8D7593",
".. c #8D738E",
"X. c #8A8C86",
"o. c #8B8D89",
"O. c #868886",
"+. c #8E918B",
"@. c #90928D",
"#. c #9C9D96",
"$. c #959793",
"%. c #A9908F",
"&. c #B8A78D",
"*. c #A995AE",
"=. c #A7A9A5",
"-. c #B1B3AD",
";. c #B5A4B7",
":. c #B4B5B1",
">. c #B9BBB7",
",. c #BDBEBB",
"<. c #D8B989",
"1. c #C9B8A9",
"2. c #DCC298",
"3. c #EDC484",
"4. c #EEC78A",
"5. c #EEC88D",
"6. c #EECB93",
"7. c #EBCC9C",
"8. c #E4C99F",
"9. c #F0CC96",
"0. c #F0CE99",
"q. c #EED68E",
"w. c #CBE188",
"e. c #D8E198",
"r. c #F7E98A",
"t. c #F6EB9A",
"y. c #FBF19D",
"u. c #FCF195",
"i. c #C3C5BE",
"p. c #DDCFB9",
"a. c #E4CBA2",
"s. c #EBCFA2",
"d. c #EBD1A5",
"f. c #EBD3AC",
"g. c #F2D4A5",
"h. c #E0CFB2",
"j. c #ECD6B3",
"k. c #ECD8B7",
"l. c #ECDABB",
"z. c #E1D2BB",
"x. c #F3DAB4",
"c. c #F1DCBB",
"v. c #E6E0AA",
"b. c #FAF1A3",
"n. c #FAF1AB",
"m. c #F4E0BC",
"M. c #FAF2B5",
"N. c #F9F3BB",
"B. c #F7F0B9",
"V. c #EDE0B4",
"C. c #C7BCC8",
"Z. c #C5C6C3",
"A. c #C9CBC5",
"S. c #CCCDC9",
"D. c #C8C6C7",
"F. c #CFD1CC",
"G. c #D1D2CE",
"H. c #CFC6D1",
"J. c #D5D5D3",
"K. c #D9DBD7",
"L. c #DCDDDB",
"P. c #DBD3DD",
"I. c #D5CAD7",
"U. c #ECDDC3",
"Y. c #EDDFC8",
"T. c #E3D5C2",
"R. c #F2DFC0",
"E. c #DFE0DD",
"W. c #EDE1CC",
"Q. c #EFE0C7",
"!. c #F1E0C6",
"~. c #F2E3CB",
"^. c #FBF6CB",
"/. c #FBF5C6",
"(. c #EEE4D4",
"). c #E1E2DF",
"_. c #F5EAD7",
"`. c #F9EEDE",
"'. c #F2E7D5",
"]. c #FCF8D3",
"[. c #E2DDE3",
"{. c #E5E6E4",
"}. c #E9E9E7",
"|. c #EDEDEB",
" X c #E8E5E8",
".X c #F9EFE0",
"XX c #F6EEE1",
"oX c #FBF2E5",
"OX c #F3F1ED",
"+X c #F9F2E8",
"@X c #F0EDF0",
"#X c #F4F3F4",
"$X c #FCFCFC",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                g g g g g g                     X.@.+.+.$.o.                    ",
"                                g N.M.M.M.g                     >.#X$X$X#XL.#.+.                ",
"                                g M.v v n.g                     -.$X$X$X$X$X$XA.@.              ",
"                                g M.v v n.g                     ,.|.#X$X$X$X|.E.+.              ",
"                                g n.b j k g                   o.K.).).|.}.}.E.A.o.              ",
"                                g b.b b y.g                   X.@XL.{.|.L.F.K.=.                ",
"                u u             g b.m b y.g                   =.OXK.}.}.K.F.E.+.                ",
"              i ) r.u           g y.N h k g                 O.Z.{.).|.).J.F.A.+.                ",
"          u H B.t.^.z           g y.N V u.g                 X.L.).).|.E.G.G.:.X.                ",
"          u M.{ v ] t.u         g y.' B u.g                 o.}.>.J.{.L.F.J.#.                  ",
"            l /.b n / /         g y.' h k g                 =.|.F.Z.:.:.:.i.+.                  ",
"            u v.{ n _ ^.i       g y.' ' u.g               X.S.{.).|.E.S.Z.>.o.                  ",
"              j ].N M r.) i     g y.` ` u.g               X.E.L.{.}.E.F.F.=.X.                  ",
"              u [ n.M > * * * * - , ` h l g               @.|.E.}.{.K.A.F.@.                    ",
"                i ^.( ..L.L.| L.K.* : - 0 i               :.{.{.|.).J.A.i.X.                    ",
"                u ( 1.;.$X X*.$X@X* S.[., p             o.S.L.{.}.E.G.A.-.X.                    ",
"                  u %.H.$XC.C.$XI.* $X$X@.8 3 3 5 4 4 3 X.).L.}.}.K.S.Z.#.                      ",
"                  7 : [.$X*.[.$X;.* #X$X*.: Q.Q.Y.Y.R.z.#.{.E.|.).J.A.i.+.6                     ",
"                  9 , |.#X} |.@X .* #X#XC.* L Y H r w w w w w w w w w e F 6                     ",
"                4 I # [.{.$ L.{.- *  X|.P.% S J r R ! ! ! ! ! Q Q Q W R e K                     ",
"                4 h.o L. XO L.{.* @ H.|.I.* & A w ! c c c c c c c c c E w 8.4                   ",
"                9 j.o {.@XO {.@X* @  .|.[., # . w w.e.v.V.m.j.e.w.w.^ ^ w m.9                   ",
"              5 P P + OX$Xo @X$X= @ = $X#X| O ; w U a a a a a a a a a D w 5.K                   ",
"              5 d.A X G.J.X J.J.# X X 1.J...O . q D y y y y y y y y a f q I a.5                 ",
"              9 oXoX+X+XoXoXoXoXOX+X+X+X+X+X+X+XXXoXoXoXoXoXXX+XoXoXoXoXoXoXoX6                 ",
"              G OX'.(.(.(.(.Y.U.U.U.l.z.T.T.z.Q.Q.Q.l.Q.l.Q.l.l.l.k.c.k.k.x.`.C                 ",
"              <.+XW.(.W.W.W.Q.Y.Q.U.U.U.Q.l.l.l.l.l.l.l.l.k.j.j.j.j.j.f.f.f.`.P                 ",
"              8.}.W.Q.Q.Y.Y.U.U.U.U.U.l.l.l.l.l.l.j.k.k.j.j.j.j.f.f.f.f.f.f.~.<.                ",
"            3 j.'.U.U.U.U.l.l.l.l.l.l.k.k.j.k.k.j.f.f.f.f.f.d.d.f.d.d.d.d.7.c.a.4               ",
"            5 W.(.U.l.l.l.l.l.k.k.k.j.j.j.j.f.f.f.f.f.f.d.d.d.d.s.s.7.s.7.7.x.j.5               ",
"            5 _.Q.k.l.j.k.j.j.j.f.f.f.f.f.f.d.d.d.d.s.s.s.s.7.7.7.7.7.7.7.7.d.c.5               ",
"            5 +X+X+X+X+X+X+X+X+X+X+XoX+XoXoXoX.X+X.XXXoX.X.XoX`.XX.X`.`.XXXX`._.5               ",
"            3 5 4 5 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 3 3 3 3               ",
"              5 &.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z A A P 3                 ",
"              5 h.L L L L L L L L L L L L L L L L L L L L L L L L L L L L L 2.3                 ",
"              5 c.Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y g.3                 ",
"              5 x.Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y 9.3                 ",
"              5 x.Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y 6.3                 ",
"              5 g.Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y 5.3                 ",
"              5 s.[ Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y T T 4                 ",
"              1 G 3.9.0.0.0.9.9.9.9.9.9.5.5.5.5.5.5.4.4.4.4.4.3.3.3.3.3.3.T s 1                 ",
"                < 3 3 3 3 3 3 3 3 3 3 3 3 3 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 3 <                   ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
