/* XPM */
static char *Fppenpd_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 138 2 ",
"   c None",
".  c #080604",
"X  c #373A3A",
"o  c #393B3B",
"O  c #484236",
"+  c #3F4141",
"@  c #454846",
"#  c #4A4D4C",
"$  c #434543",
"%  c #525454",
"&  c #555857",
"*  c #55595A",
"=  c #5A5E5E",
"-  c #645744",
";  c #60625E",
":  c #5E6262",
">  c #646766",
",  c #666A6A",
"<  c #6A6D6D",
"1  c #6C706F",
"2  c #6F7472",
"3  c #7C7E7B",
"4  c #E23A1F",
"5  c #EE2E2E",
"6  c #E9312B",
"7  c #EE3130",
"8  c #CE5F03",
"9  c #CE630C",
"0  c #D1650D",
"q  c #D16710",
"w  c #D36911",
"e  c #AE6C4D",
"r  c #A8764A",
"t  c #897D6B",
"y  c #AC6F61",
"u  c #A37769",
"i  c #AB726F",
"p  c #B3706E",
"a  c #A27976",
"s  c #D55756",
"d  c #F04B4A",
"f  c #DE6E6E",
"g  c #F29C31",
"h  c #FBAE3E",
"j  c #9E8065",
"k  c #97816B",
"l  c #998479",
"z  c #B79469",
"x  c #AE9075",
"c  c #DE9545",
"v  c #C08D5B",
"b  c #C79959",
"n  c #E28F42",
"m  c #E39044",
"M  c #EC9E47",
"N  c #EC9F49",
"B  c #DFA650",
"V  c #ECA04B",
"C  c #F3AD56",
"Z  c #F3AE59",
"A  c #CBA060",
"S  c #DBA967",
"D  c #CCA371",
"F  c #DCB177",
"G  c #E5AD61",
"H  c #E7B064",
"J  c #E7B46B",
"K  c #FDBE62",
"L  c #EAB871",
"P  c #FDC26B",
"I  c #828482",
"U  c #8C8A83",
"Y  c #8A8B89",
"T  c #938F8B",
"R  c #8F908B",
"E  c #92928D",
"W  c #98928E",
"Q  c #939594",
"!  c #969897",
"~  c #9C9D9B",
"^  c #A29683",
"/  c #A69F9B",
"(  c #9DA09E",
")  c #BEA088",
"_  c #B3A897",
"`  c #BCAA96",
"'  c #A4A5A4",
"]  c #A6A8A7",
"[  c #A8AAA7",
"{  c #A7A8A8",
"}  c #AAABA9",
"|  c #B3B4B2",
" . c #B7B8B5",
".. c #B8B9B7",
"X. c #BCBDBC",
"o. c #D38686",
"O. c #EC8080",
"+. c #E59494",
"@. c #CDAF96",
"#. c #CBAF98",
"$. c #C4AA93",
"%. c #BEC0BC",
"&. c #F2C78E",
"*. c #EFCA9A",
"=. c #F0D19F",
"-. c #C1C2BE",
";. c #E7C9B0",
":. c #EDCFB5",
">. c #EACFB9",
",. c #EED0B4",
"<. c #EED2BC",
"1. c #F0D2B9",
"2. c #F5E0BE",
"3. c #C4C5C2",
"4. c #C6C8C6",
"5. c #C9C9C6",
"6. c #CCCDCA",
"7. c #CFD0CF",
"8. c #D2D6CF",
"9. c #D5D6D4",
"0. c #D6DAD2",
"q. c #D9DCD6",
"w. c #DBDCD9",
"e. c #F1D6C0",
"r. c #DDE1DB",
"t. c #F6E4C9",
"y. c #E1E3DE",
"u. c #DFE0E0",
"i. c #E4E4E3",
"p. c #E9E8E6",
"a. c #EDEEEC",
"s. c #EFF0ED",
"d. c #F0F0EF",
"f. c #FFF8EE",
"g. c #FBF3E7",
"h. c #F4F4F3",
"j. c #F8F8F7",
"k. c #FBFBFA",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                } ]     } }     } [     } [     } [     } [     } [                             ",
"                9.i.4.  9.i.4.  9.i.4.  9.i.4.  9.i.4.  9.i.4.  9.i.4.                          ",
"             .| w.j. .| w.k...| w.j. .| w.j. .| q.k. .| q.k. .| w.j. .| ..              7 7     ",
"           .d.k.~ r.~ j.( w.( j.~ r.~ k.~ w.~ k.~ w.~ k.~ r.~ j.( r.~ k.a. .        6 5 f O.d 7 ",
"          X.k.a.3 %.Y h.t X.Y h.3 %.Y h.3 %.Y h.3 %.Y h.3 %.Y h.3 %.Y h.k.|       y u p o.+.+.5 ",
"          5.k.h.[ > X.k.} ; %.k.] ; X.k.[ ; X.k.} ; X.j.] > X.j.} : X.j.k...    u W 6./ l o.o.5 ",
"          6.k.a.h.k.k.s.j.k.k.d.j.k.k.d.k.k.k.d.j.k.k.h.j.k.k.d.j.k.k.h.k.3.  k Y i.k.9.T a s 6 ",
"          9.k.a.a.a.a.a.d.a.d.a.s.d.s.d.d.d.d.d.d.d.d.d.d.d.d.d.s.d.d.d.k.3.k k ^ R %.' 3 U 6   ",
"          w.k.a.a.d.a.d.a.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.h.s.s.h.d.d.d.d.k.#.9 C P V U 3 ~ U     ",
"        I i.h.a.-.X.%.X.%.5.d.-.5.d.-.5.3.%.%.%.6.d.d.3.5.d.3.X.%.%.5.d.e.9 C K h g z R U e     ",
"        I p.h.d.d.d.d.d.d.d.d.d.d.d.d.h.d.d.h.h.d.h.h.d.h.d.h.h.h.h.d.>.q Z P h g V v U         ",
"        Y a.h.a.-.5.d.4.-.-.6.j.3.6.h.-.-.-.6.h.d.h.h.h.d.h.h.d.d.h.<.q C P C g N n r           ",
"        R h.h.d.d.d.d.d.d.d.d.d.h.d.h.h.h.d.d.h.h.h.d.h.h.h.h.h.h.<.0 C K h g c n 8             ",
"        Q h.h.d.d.d.d.d.d.d.d.d.h.d.d.h.h.h.d.h.h.d.h.h.h.h.h.h.,.q C K h g V n 8               ",
"        Q k.h.y.-.-.-.-.-.-.-.6.h.h.5.-.-.6.5.7.h.5.-.8.h.4.-.$.9 C K h g M g 8                 ",
"        ~ k.h.d.d.d.d.d.d.h.h.d.h.h.h.h.h.h.h.h.h.j.j.h.j.h.<.q C K h g V m 9                   ",
"        ! k.h.w.-.-.5.j.4.6.h.4.-.-.6.5.7.j.h.5.6.h.j.j.j.<.q C P h g V m q u                   ",
"        ! k.d.d.d.h.h.h.h.h.h.h.h.h.j.h.h.j.j.h.j.j.j.h.<.w C K N g V m 9 <.Y                   ",
"        ( k.h.d.j.d.h.h.h.h.h.j.h.j.h.j.j.h.j.j.j.j.k.<.w C K h g N g q ,.k.Y                   ",
"        } k.h.9.-.5.h.4.7.3.-.-.7.j.4.7.j.j.j.j.k.j.<.w Z K h g N m 9 >.j.k.Y                   ",
"        | k.h.h.h.h.h.h.j.h.j.h.h.j.j.j.j.j.j.k.k.<.w C P h g M m 9 >.j.k.k.Q                   ",
"      # X.k.h.h.h.h.h.h.h.j.j.j.j.j.j.j.k.j.j.j.:.w Z K N g M g 9 e.j.j.h.k.~                   ",
"      % 5.j.h.h.h.h.h.j.h.j.h.j.j.j.j.j.k.j.k.k.H &.P h g N m 9 ;.p.i.p.a.j.{                   ",
"      * 9.k.h.h.h.h.j.h.j.h.j.j.j.k.j.k.j.k.k.t.J k.g.C V m 0 @.7.9.u.i.a.h.| +                 ",
"      = u.k.h.3.6.h.4.-.-.7.j.j.4.-.3.3.7.k.5.F *.g.t.&.m 0 x 3.{ { } X.p.h.X.$                 ",
"      > p.j.h.h.h.j.h.j.j.j.j.j.j.k.j.k.k.k.p.A 1.=.L G c ) %.3.4.7.u.i.a.h.4.@                 ",
"      < a.h.h.h.h.h.j.h.j.j.j.k.j.j.j.k.k.j.k . b L S D ` ..3.9.u.p.s.s.d.h.7.#                 ",
"      < s.j.s.-.%.3.6.j.4.3.3.3.3.7.j.k.5.3.O - _ 6.9.i.a.h.h.h.h.h.h.d.d.j.w.%                 ",
"      1 h.j.h.h.h.h.h.j.h.j.j.j.j.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.j.j.j.j.j.k.u.=                 ",
"      < j.h.h.h.h.j.h.h.j.j.j.j.j.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.p.:                 ",
"      , k.h.h.h.j.h.j.j.h.j.j.j.j.k.j.k.j.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.a.:                 ",
"      , k.h.h.h.h.h.h.j.j.j.j.j.j.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.d.:                 ",
"      2 a.0.8.8.0.0.8.8.0.0.0.0.q.0.0.0.q.q.q.q.r.r.r.q.r.y.r.r.y.i.r.y.y.i.s.=                 ",
"      1 a.8.8.8.8.0.0.0.0.8.0.0.0.0.0.0.q.q.q.q.w.q.r.r.r.r.r.r.r.r.y.y.y.y.s.*                 ",
"      < a.p.a.a.p.a.p.a.a.a.a.a.p.s.a.a.a.s.s.a.s.s.s.a.s.s.s.s.s.d.s.s.s.s.s.&                 ",
"      X X X o o X X o o o o o o X X X X X X X X X X X X X X X X X X X X X X X o                 ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
