/* XPM */
static char *Fpstyle_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 187 2 ",
"   c None",
".  c #37213E",
"X  c #152F53",
"o  c #34374B",
"O  c #1B3C6D",
"+  c #183662",
"@  c #1B3E71",
"#  c #48364C",
"$  c #4B2C53",
"%  c #493853",
"&  c #56325F",
"*  c #5C3566",
"=  c #603B6A",
"-  c #1E447B",
";  c #324B6F",
":  c #344252",
">  c #474847",
",  c #524B53",
"<  c #5C5D5A",
"1  c #565655",
"2  c #504E4B",
"3  c #5F605D",
"4  c #6F645C",
"5  c #56516D",
"6  c #635966",
"7  c #75507B",
"8  c #68476D",
"9  c #626463",
"0  c #686B6A",
"q  c #72726D",
"w  c #787A76",
"e  c #7B7D79",
"r  c #777778",
"t  c #716C74",
"y  c #853B00",
"u  c #8C4B17",
"i  c #A54A00",
"p  c #A6520E",
"a  c #9C7F00",
"s  c #AA632A",
"d  c #CE5C00",
"f  c #C76307",
"g  c #C56F1B",
"h  c #F57900",
"j  c #D47020",
"k  c #866E59",
"l  c #9E6F4A",
"z  c #BF7D48",
"x  c #957F6C",
"c  c #7F817C",
"v  c #C4A000",
"b  c #D98037",
"n  c #F6912E",
"m  c #F59538",
"M  c #FCAF3E",
"N  c #F58414",
"B  c #EDD400",
"V  c #81837F",
"C  c #928678",
"Z  c #A3917A",
"A  c #DD9357",
"S  c #C78E55",
"D  c #FCB246",
"F  c #F8AF58",
"G  c #CD9A6F",
"H  c #E29E68",
"J  c #F5AD66",
"K  c #F1B574",
"L  c #FCE94F",
"P  c #FDC779",
"I  c #FCC675",
"U  c #FDC26B",
"Y  c #1F4884",
"T  c #204A87",
"R  c #2B5487",
"E  c #2F5B94",
"W  c #3465A4",
"Q  c #6F5A85",
"!  c #777687",
"~  c #796D94",
"^  c #847B89",
"/  c #947C9D",
"(  c #86678C",
")  c #8A7DA1",
"_  c #AD7FA8",
"`  c #7D8286",
"'  c #7D91AA",
"]  c #7C8EA5",
"[  c #729FCF",
"{  c #848681",
"}  c #888A85",
"|  c #8C8D8A",
" . c #878983",
".. c #8E908B",
"X. c #91928D",
"o. c #8A8698",
"O. c #949692",
"+. c #969994",
"@. c #999A96",
"#. c #999B9A",
"$. c #958B9B",
"%. c #A59786",
"&. c #BF9E83",
"*. c #9EA09B",
"=. c #A1A29C",
"-. c #A6A396",
";. c #948CA7",
":. c #938EA6",
">. c #AB81A9",
",. c #A786AE",
"<. c #A798AE",
"1. c #AB99B9",
"2. c #BB9BBC",
"3. c #AF8BB1",
"4. c #A4A6A2",
"5. c #A6A8A4",
"6. c #A8ABA5",
"7. c #ABADA9",
"8. c #A7A3AD",
"9. c #AFB1AB",
"0. c #B6B4AC",
"q. c #ABABB7",
"w. c #B7A7BC",
"e. c #BABDB6",
"r. c #BCBEBB",
"t. c #B5B5B5",
"y. c #B5AFA2",
"u. c #CCB294",
"i. c #EBB684",
"p. c #CEBEA5",
"a. c #BEC1BA",
"s. c #FCCB84",
"d. c #F6C88A",
"f. c #F5CA94",
"g. c #FBD399",
"h. c #FDF08B",
"j. c #C1C3BF",
"k. c #DBC1AB",
"l. c #F9D6A4",
"z. c #E7D6BA",
"x. c #F2D9BA",
"c. c #E9CEAB",
"v. c #FEE2B8",
"b. c #9EBDDE",
"n. c #8FA7C4",
"m. c #B3AFC5",
"M. c #C4A4C1",
"N. c #C6ABC6",
"B. c #C2B4CB",
"V. c #CBBDD2",
"C. c #D3BED3",
"Z. c #D1B7CE",
"A. c #B8CFE7",
"S. c #C8C9C9",
"D. c #CAC7D8",
"F. c #D5C8D8",
"G. c #D8D8DB",
"H. c #E7DFC0",
"J. c #E3D6C1",
"K. c #EFDFCA",
"L. c #F1E8C0",
"P. c #F1E3CC",
"I. c #FEE5C0",
"U. c #FBF5C0",
"Y. c #E9E5DD",
"T. c #F2EADE",
"R. c #FDEFD9",
"E. c #F2E5D2",
"W. c #FFFAD3",
"Q. c #FCF0DE",
"!. c #CEDEEE",
"~. c #D5DDE8",
"^. c #D8DBE2",
"/. c #E3DAE5",
"(. c #D9E2EE",
"). c #EEEEEC",
"_. c #E7E5E7",
"`. c #F4EBE1",
"'. c #FFFCE2",
"]. c #F1F1EF",
"[. c #F9F1E7",
"{. c #E4EDF6",
"}. c #EDECF0",
"|. c #EDF3F9",
" X c #F4F5F4",
".X c #F8F8F7",
"XX c #FCFCFC",
/* pixels */
"                                                                                                ",
"        a.e.e.e.e.a.e.e.a.                                                                      ",
"      a..XXXXXXXXXXXXXXX Xa.                                                                    ",
"      e.XXXXXXXXXXXXXXXXXXr.                                                                    ",
"      e.'.h.h.h.h.h.h.h.'.e.                                                                    ",
"      e.'.h.h.h.h.h.h.h.'.a.              @.4.O.                                                ",
"      e.'.h.h.h.h.h.h.h.'.e.            +.]..X).5.+.                                            ",
"      r.'.h.h.h.h.h.h.h.W.t.          +.z.[.). XXX^.#.+.                                        ",
"      e.'.h.h.h.h.h.h.h.'.0.          -.R.g.s.L.]..X.XS.+.                                      ",
"      t.XXXXXXXXXX.XXXXXXX9.        @.K.v.P P P g.P. XXX X+.                                    ",
"      0.W.L L L L L L L W.7.        y.R.s.P P P I P l.`..X7.                                    ",
"      9.W.L L L L L L L W.6.      @.R.x.P P P P I P I l.`.+.                                    ",
"      9.W.L L L L L L L W.4.      p.R.T.g.P P P P P s.R.0.                                      ",
"      6.W.L L L L L L L W.*.    @.l.F K P.P.g.I P P v.P.+.                                      ",
"      5.W.L L L L L L L W.*.  +.c.s.M M M d.Y.x.s.g.R.=.                                        ",
"      =.XX.X.X.X.X X.X.XXX*.  -.g.D M M M D D l.`.R.J.{                                         ",
"      *.U.B B B B B B B v.@.e x.P M M M M M M M I T...                                          ",
"      *.U.B B B B B B B v.X.C '.v.U M M M M M D s.p.                @.7.@.                      ",
"      @.U.B B B B B B B U.*.Z m J Y.g.D M M M U l.c             #.t._.XX X@.                    ",
"      +.U.B B B B B B B v...S h h N d.Y.P M D g.%.          +.4.F./.C./.XXS.+.                  ",
"      X.U.B B B B B B B U.| g h h h h n z.K.g.c.0         @.F./.F.M.M.B.[..X*.                  ",
"      ..XX X|. X X X X XXX} f h h h h h h J [.c       #.m._._.N.M.M.M.M.G..X(.+.                ",
"      | L.v v v v v v v v.{ d h h h h h h J u.3   @.q.C.C.2._.M.M.M.M.M.m.]..X8.                ",
"      } L.v v v v v v v P.} 0.F h h h h n i.4 w | V.F.M.>._ m.D.M.M.M.M.M.D. X).+.              ",
"      | x.v v v v v v v L.} s z.x.m h h K Z 0 o.}.V.3._ _ _ _ ~.m.M.M.M.M.M.).XX5.              ",
"      } L.v v v v v v v L.} i d A /.i.F i.3 $.<.o.F._ _ _ _ _ 1.^.N.M.M.M.N._.G.@.              ",
"       .v.v v v v v v v L.} i d d f i. Xq ^ Q 7 Q m.1._ _ _ _ _ D.B.M.M.F.F.t.O.                ",
"      | XX|.].].].].].].XX} i d d d A G 3 8 8 7 7 Q ^._ _ _ _ _ 3./.C./.N.$.@.                  ",
"      } H.a a a a a a a H.} i d d j i.< ! 8 7 7 7 7 ;.m._ _ _ _ 2._.S.#.@.                      ",
"      } H.a a a a a a a H.| p d d H x % <.Q 7 7 7 7 Q G.,._ 3.Z.B.#.|                           ",
"      } H.a a a a a a a H.} p.G b G 1 $ 5 m.7 7 7 7 7 ) D.N.F.<.{                               ",
"      } H.a a a a a a a H.} u k.`.4 % $ & w.~ 7 7 7 7 / ).q.! X.                                ",
"      | z.a a a a a a a H.} y S %., $ & * 8 D.Q 7 ( w.8.! }                                     ",
"      } XX).].].).).).).XX} u Z 1 $ $ * * * ;.;.3.w.! e                                         ",
"      | XX).].].).).).]..X .l k 0 % & * * = /  Xo.q O.+.O.*.0.e.e.e.e.e.e.e.e.e.e.e.a.          ",
"      } XX).).S.a.9.).).XX{ l 2 % o.* * Q w.;.0 ` ] ' ' n. XA.A.A.A.A. X!.!.!.!.!. X).a.        ",
"      | .X).).j.G.w ).)..XV 2 # . q.~ <.<.t 0 0.R R E W W ).[ [ [ [ [ ).b.b.b.b.b.)..Xe.        ",
"      ..G.].).9.e 7.).]._.9 > . $ :._.! 9 ; O j.E W W W W ).[ [ [ [ [ ).b.b.b.b.b.)..X0.        ",
"      X.O. X).).).).)..X=.> . 6 8.{ 9 5 - O - ^.W W W W W ).[ [ [ [ [ ).b.b.b.b.b.)..X6.        ",
"      +.< G..X].].[..XG.< > ^ | 3 w - O O - T ).W W W W W ).[ [ [ [ [ ].b.b.b.b.b.)..X#.        ",
"      O.< w a._. X_.5.q > | 3 1 o j.@ - Y T T ).W W W W W ).[ [ [ [ [ ).b.b.b.b.b.).XXX.        ",
"      | 3 w O.4.5.| q 0 3 > : X X S.Y T T T T ).W W W W W ).[ [ [ [ [ ).b.b.b.b.b.]..X}         ",
"      e w 0 O.e.j.*.q 9 > X X X + ).T T T T T ).W W W W W ).[ [ [ [ [ ).b.b.b.b.b.)..X}         ",
"        { } +.6.9.+.| =.q.q.S.!.^.XX~.~.!.~.~.XX(.(.(.(.(.XX{.{.{.{.{.XX|.|.|.|.|.XX). .        ",
"          ..7.j.S.6.c c w c w w w w w w w w w e e e e c e c c c c c c V V V V V { V @. .        ",
"            w V  . .V | ` }  .` } }  .} | } } } } } }  .} } } } | } } }  .| |  .} |  .          ",
"                                                                                                ",
"                                                                                                "
};
