/* XPM */
static char *Fptrsh_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 175 2 ",
"   c None",
".  c #717573",
"X  c #737574",
"o  c #7C7B7E",
"O  c #7D7B7F",
"+  c #7D7C7F",
"@  c #259A64",
"#  c #249B64",
"$  c #259B65",
"%  c #259B66",
"&  c #259C65",
"*  c #269C64",
"=  c #269C65",
"-  c #259C66",
";  c #259D66",
":  c #269D66",
">  c #269C67",
",  c #269D67",
"<  c #259E66",
"1  c #269E67",
"2  c #269F67",
"3  c #269F68",
"4  c #37946A",
"5  c #38956A",
"6  c #26A067",
"7  c #26A068",
"8  c #26A168",
"9  c #27A56B",
"0  c #30A66F",
"q  c #31A871",
"w  c #2BB273",
"e  c #2BB475",
"r  c #2CB979",
"t  c #2CBA79",
"y  c #2DBE7B",
"u  c #2DBF7D",
"i  c #34B87A",
"p  c #2EC17D",
"a  c #2DC07E",
"s  c #2EC27E",
"d  c #2FC27F",
"f  c #30C27F",
"g  c #34BF80",
"h  c #32C381",
"j  c #34C482",
"k  c #36C483",
"l  c #37C584",
"z  c #39C282",
"x  c #39C383",
"c  c #39C585",
"v  c #3BC686",
"b  c #3CC687",
"n  c #3DC687",
"m  c #3FC789",
"M  c #3BCD8A",
"N  c #40C789",
"B  c #43C88B",
"V  c #44C88B",
"C  c #46C98D",
"Z  c #47C98E",
"A  c #4BCA90",
"S  c #55CD96",
"D  c #59CE98",
"F  c #5ACF99",
"G  c #62D19E",
"H  c #65D2A0",
"J  c #68D3A2",
"K  c #6BD4A4",
"L  c #7CD9AE",
"P  c #7FDAB0",
"I  c #838385",
"U  c #868686",
"Y  c #8A898B",
"T  c #8F8E8F",
"R  c gray58",
"E  c #959595",
"W  c gray59",
"Q  c #979797",
"!  c #989794",
"~  c #9A9996",
"^  c #9B9A97",
"/  c #989898",
"(  c #9E9D9A",
")  c #9F9E9B",
"_  c #A09F9C",
"`  c #A1A09D",
"'  c #A6A6A7",
"]  c #ADACAA",
"[  c #AFAEAE",
"{  c #B0AFAD",
"}  c #ACB6B0",
"|  c #B5B4B2",
" . c #B5B5B3",
".. c #B6B9B5",
"X. c #82DBB2",
"o. c #84DBB3",
"O. c #88DCB6",
"+. c #8ADDB7",
"@. c #8CDEB8",
"#. c #8EDEB9",
"$. c #90DFBB",
"%. c #91DFBB",
"&. c #A2CCB8",
"*. c #AACEBC",
"=. c #95E0BE",
"-. c #9AE2C1",
";. c #9DE2C2",
":. c #9DE3C3",
">. c #9FE3C3",
",. c #A5E5C7",
"<. c #A6E5C8",
"1. c #ABE6CB",
"2. c #ABE7CB",
"3. c #B6EAD2",
"4. c #B8EAD3",
"5. c #BAEBD4",
"6. c #BAEBD5",
"7. c #CFCECC",
"8. c #CFCECD",
"9. c #D0CFCD",
"0. c #D2D1CD",
"q. c #D2D1CE",
"w. c #D1D1D0",
"e. c #D6D6D2",
"r. c #D5D5D4",
"t. c #D6D5D4",
"y. c #DCDCDA",
"u. c #DDDCDA",
"i. c #DEDDDA",
"p. c #DFDEDB",
"a. c #C2EDDA",
"s. c #C3EEDA",
"d. c #C9EFDE",
"f. c #D9E2DC",
"g. c #DBE3DD",
"h. c #CBF0DF",
"j. c #E2E1DF",
"k. c #CCF0E0",
"l. c #CFF1E2",
"z. c #D2F2E3",
"x. c #D6F3E6",
"c. c #DBF4E9",
"v. c #DDF5EA",
"b. c #E7E7E5",
"n. c #E8E7E5",
"m. c #E8E7E6",
"M. c #E9E8E7",
"N. c #EAE9E8",
"B. c #EBEAE9",
"V. c #EBEBE9",
"C. c #ECEBEA",
"Z. c #EDEBEA",
"A. c #ECECEA",
"S. c #EDECEA",
"D. c #EDECEB",
"F. c #EEEDEC",
"G. c #EEEDED",
"H. c #F0EFEE",
"J. c #E3F7EE",
"K. c #EBF9F3",
"L. c #EEFAF4",
"P. c #EFFAF5",
"I. c #F4F3F3",
"U. c #F6F5F4",
"Y. c #F2FBF7",
"T. c #F5FCF9",
"R. c #F6FCF9",
"E. c #F7FDFA",
"W. c #F9FDFB",
"Q. c #FAFEFC",
"!. c #FCFEFD",
"~. c #FDFEFD",
"^. c #FDFEFE",
"/. c #FDFFFE",
"(. c white",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q               ",
"              Q t.F.H.H.H.H.H.H.F.H.H.H.H.H.H.H.H.H.H.H.F.H.H.H.H.H.H.H.H.H.H.F.e.Q             ",
"            Q w.[ T ) ) ` ) ` ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` ` ` { 7.7.Q           ",
"            R B.o I ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ^ ] | B.R           ",
"            Q F.o I ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ^ ] | B.R           ",
"            Q F.o I Q ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ^ ] | B.Q           ",
"            Q F.o I ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ^ ] | B.R           ",
"            Q F.o I ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ] | A.R           ",
"            Q F.o I ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ] | A.Q           ",
"            R D.o I ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ] | D.Q           ",
"            Q Z.' Y ) ` ` ) ` ) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ` ` { 9.b.Q           ",
"            Q p.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.I.e.R           ",
"            Q y.Z.Z.M.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.n.B.B.9.Q           ",
"            R i.B.M.j.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p.n.Z.0.Q           ",
"            U } B.M.j.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p.n.M...U           ",
"              . &.f.j.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p.g.*.X             ",
"              5 q 0 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ @ $ $ @ @ 9 4             ",
"              7 x M s s s s s s s s s s s s s s s s s s s s s s s s s s s s p y t 7             ",
"              7 x M s s s s s s s s s s s s s s s s s s s s s s s s s s s s p y t 7             ",
"              7 x M s s s s s s s s s s s s s s s s s s s s s s s s s s s s p y t 3             ",
"              7 x M s s s s s s s s s s s s s s s s s s s s s s s s s s s s p y t 3             ",
"              6 x M s s s s s s s s s s s #.L.(.(.(.(.d.V s s s s s s s s s p y t 2             ",
"              6 x M s s s s s s s s s s H (.(.(.(.(.(.(.k.s s s s s s s s s p y t 2             ",
"              6 x M s s s s s s s s s s l.(.(.(.c.(.(.(.(.;.K s s s s s s s s y t 2             ",
"              2 x M s s s s s s s s s s n ,.Q.(.D a.(.(.(.Q.m s s s s s s s p y t 2             ",
"              2 x M s s s s s s s s V H o.N S +.s D (.(.(.6.s s s s s s s s u y t 2             ",
"              2 x M s s s s s s f %.(.(.(.%.s s h o.3.x.T.J s l s s s s s s s y t 2             ",
"              2 x M s s s s s s s P (.(.(.J.s s s s s s s V 2.v.f f s s s s s y t 2             ",
"              2 x M s s s s s s h K.(.(.(.T.G s s s s s %.T.(.(.X.s s s s s u y t 2             ",
"              2 x M s s s s s s S (.(.(.T.Z A s s s l s 2.(.(.(.3.s s s s s p y r 2             ",
"              2 x M s s s s s s j L.(.(.=.s s s s n 2.s m Y.(.(.O.s s s s s p y r @             ",
"              $ x M s s s s s s s 6.(.(.(.(.d.s f a.(.(.(.(.(.W.c s s s s s p y r $             ",
"              2 x M s s s s s s s j W.(.(.(.d.s ;.(.(.(.(.(.(.,.s s s s s s p y r 2             ",
"              2 x M s s s s s s s s L (.(.(.d.s -.(.(.(.(.(.z.s s s s s s s f y r 2             ",
"              $ x M s s s s s s s s s #.L.(.d.s f a.(.(.(.h.N s s s s s s s u y r $             ",
"              $ x M s s s s s s s s s s s s s s s c <.s s s s s s s s s s s s y r $             ",
"              2 x M s s s s s s s s s s s s s s s s k s s s s s s s s s s s s y r $             ",
"              $ x M s s s s s s s s s s s s s s s s s s s s s s s s s s s s s y r 2             ",
"              $ i M s s s s s s s s s s s s s s s s s s s s s s s s s s s s p y w #             ",
"                $ i h s s s s s s s s s s s s s s s s s s s h s s s s s s s u e $               ",
"                  2 ; # $ $ $ # $ $ $ $ $ $ $ $ $ $ $ $ # # $ $ $ $ $ $ $ @ @ 2                 ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
